# coding: utf-8

# flake8: noqa
"""
    ITM TA3 MVP API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  It is based on the OpenAPI 3.0 specification.  Some objects and operations are not necessarily planned for the MVP, but are currently present for fostering discussion.  The API is currently in an draft state, even in the context of an MVP.  # noqa: E501

    OpenAPI spec version: 0.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.environment import Environment
from swagger_client.models.injury import Injury
from swagger_client.models.medical_supply import MedicalSupply
from swagger_client.models.patient import Patient
from swagger_client.models.probe import Probe
from swagger_client.models.scenario import Scenario
from swagger_client.models.scenario_state import ScenarioState
from swagger_client.models.triage_category import TriageCategory
from swagger_client.models.vitals import Vitals
