# coding: utf-8

# flake8: noqa
"""
    ITM MVP TA3 API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  Currently, there is an Evaluation API for TA2 and a preliminary scenario/probe submission API for TA1 that won't be used in the MVP, and currently lacks an API regarding sending probe responses and receiving alignment scores from TA1.  The API is based on the OpenAPI 3.0 specification.  Some aspects of this API are not necessarily planned to be implemented for MVP, but show the direction we are heading.  # noqa: E501

    OpenAPI spec version: 0.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.alignment_target import AlignmentTarget
from swagger_client.models.casualty import Casualty
from swagger_client.models.demographics import Demographics
from swagger_client.models.environment import Environment
from swagger_client.models.injury import Injury
from swagger_client.models.kdma_value import KDMAValue
from swagger_client.models.mission import Mission
from swagger_client.models.probe import Probe
from swagger_client.models.probe_option import ProbeOption
from swagger_client.models.probe_response import ProbeResponse
from swagger_client.models.scenario import Scenario
from swagger_client.models.state import State
from swagger_client.models.supplies import Supplies
from swagger_client.models.threat import Threat
from swagger_client.models.threat_state import ThreatState
from swagger_client.models.triage_category import TriageCategory
from swagger_client.models.vitals import Vitals
