# coding: utf-8

"""
    ITM MVP TA3 API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  Currently, there is an Evaluation API for TA2 and a preliminary scenario/probe submission API for TA1 that won't be used in the MVP, and currently lacks an API regarding sending probe responses and receiving alignment scores from TA1.  The API is based on the OpenAPI 3.0 specification.  Some objects and operations are not necessarily planned to be implemented for MVP, but show the direction we are heading.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AlignmentTarget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'kdma_values': 'list[AlignmentTargetKdmaValues]'
    }

    attribute_map = {
        'id': 'id',
        'kdma_values': 'kdma_values'
    }

    def __init__(self, id=None, kdma_values=None):  # noqa: E501
        """AlignmentTarget - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._kdma_values = None
        self.discriminator = None
        self.id = id
        self.kdma_values = kdma_values

    @property
    def id(self):
        """Gets the id of this AlignmentTarget.  # noqa: E501

        globally unique alignment target  # noqa: E501

        :return: The id of this AlignmentTarget.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlignmentTarget.

        globally unique alignment target  # noqa: E501

        :param id: The id of this AlignmentTarget.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def kdma_values(self):
        """Gets the kdma_values of this AlignmentTarget.  # noqa: E501

        list of KDMAs to align to  # noqa: E501

        :return: The kdma_values of this AlignmentTarget.  # noqa: E501
        :rtype: list[AlignmentTargetKdmaValues]
        """
        return self._kdma_values

    @kdma_values.setter
    def kdma_values(self, kdma_values):
        """Sets the kdma_values of this AlignmentTarget.

        list of KDMAs to align to  # noqa: E501

        :param kdma_values: The kdma_values of this AlignmentTarget.  # noqa: E501
        :type: list[AlignmentTargetKdmaValues]
        """
        if kdma_values is None:
            raise ValueError("Invalid value for `kdma_values`, must not be `None`")  # noqa: E501

        self._kdma_values = kdma_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlignmentTarget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlignmentTarget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
