# coding: utf-8

"""
    ITM MVP TA3 API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  Currently, there is an Evaluation API for TA2 and a preliminary scenario/probe submission API for TA1 that won't be used in the MVP, and currently lacks an API regarding sending probe responses and receiving alignment scores from TA1.  The API is based on the OpenAPI 3.0 specification.  Some aspects of this API are not necessarily planned to be implemented for MVP, but show the direction we are heading.  # noqa: E501

    OpenAPI spec version: 0.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TriageCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag_label': 'str',
        'description': 'str',
        'criteria': 'str'
    }

    attribute_map = {
        'tag_label': 'tagLabel',
        'description': 'description',
        'criteria': 'criteria'
    }

    def __init__(self, tag_label=None, description=None, criteria=None):  # noqa: E501
        """TriageCategory - a model defined in Swagger"""  # noqa: E501
        self._tag_label = None
        self._description = None
        self._criteria = None
        self.discriminator = None
        if tag_label is not None:
            self.tag_label = tag_label
        if description is not None:
            self.description = description
        if criteria is not None:
            self.criteria = criteria

    @property
    def tag_label(self):
        """Gets the tag_label of this TriageCategory.  # noqa: E501


        :return: The tag_label of this TriageCategory.  # noqa: E501
        :rtype: str
        """
        return self._tag_label

    @tag_label.setter
    def tag_label(self, tag_label):
        """Sets the tag_label of this TriageCategory.


        :param tag_label: The tag_label of this TriageCategory.  # noqa: E501
        :type: str
        """
        allowed_values = ["minimal", "delayed", "immediate", "expectant", "deceased"]  # noqa: E501
        if tag_label not in allowed_values:
            raise ValueError(
                "Invalid value for `tag_label` ({0}), must be one of {1}"  # noqa: E501
                .format(tag_label, allowed_values)
            )

        self._tag_label = tag_label

    @property
    def description(self):
        """Gets the description of this TriageCategory.  # noqa: E501

        a one-line description of the tagLabel category  # noqa: E501

        :return: The description of this TriageCategory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TriageCategory.

        a one-line description of the tagLabel category  # noqa: E501

        :param description: The description of this TriageCategory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def criteria(self):
        """Gets the criteria of this TriageCategory.  # noqa: E501

        detailed criteria for the tagLabel category  # noqa: E501

        :return: The criteria of this TriageCategory.  # noqa: E501
        :rtype: str
        """
        return self._criteria

    @criteria.setter
    def criteria(self, criteria):
        """Sets the criteria of this TriageCategory.

        detailed criteria for the tagLabel category  # noqa: E501

        :param criteria: The criteria of this TriageCategory.  # noqa: E501
        :type: str
        """

        self._criteria = criteria

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TriageCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TriageCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
