# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MedicalSupply(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, quantity: int=None):  # noqa: E501
        """MedicalSupply - a model defined in Swagger

        :param name: The name of this MedicalSupply.  # noqa: E501
        :type name: str
        :param description: The description of this MedicalSupply.  # noqa: E501
        :type description: str
        :param quantity: The quantity of this MedicalSupply.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'quantity': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'quantity': 'quantity'
        }
        self._name = name
        self._description = description
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'MedicalSupply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MedicalSupply of this MedicalSupply.  # noqa: E501
        :rtype: MedicalSupply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MedicalSupply.

        a short label for the item  # noqa: E501

        :return: The name of this MedicalSupply.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MedicalSupply.

        a short label for the item  # noqa: E501

        :param name: The name of this MedicalSupply.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MedicalSupply.

        a brief natural language description of the item  # noqa: E501

        :return: The description of this MedicalSupply.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MedicalSupply.

        a brief natural language description of the item  # noqa: E501

        :param description: The description of this MedicalSupply.
        :type description: str
        """

        self._description = description

    @property
    def quantity(self) -> int:
        """Gets the quantity of this MedicalSupply.

        the number of these items available to the medic at the present time  # noqa: E501

        :return: The quantity of this MedicalSupply.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this MedicalSupply.

        the number of these items available to the medic at the present time  # noqa: E501

        :param quantity: The quantity of this MedicalSupply.
        :type quantity: int
        """

        self._quantity = quantity
