# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Supplies(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, quantity: int=None):  # noqa: E501
        """Supplies - a model defined in Swagger

        :param type: The type of this Supplies.  # noqa: E501
        :type type: str
        :param quantity: The quantity of this Supplies.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'type': str,
            'quantity': int
        }

        self.attribute_map = {
            'type': 'type',
            'quantity': 'quantity'
        }
        self._type = type
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'Supplies':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Supplies of this Supplies.  # noqa: E501
        :rtype: Supplies
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Supplies.

        an enum of available supply types  # noqa: E501

        :return: The type of this Supplies.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Supplies.

        an enum of available supply types  # noqa: E501

        :param type: The type of this Supplies.
        :type type: str
        """
        allowed_values = ["IV kits", "Bags of Saline", "Fast Kit", "Junctional Tourniquets", "Combat Gauze", "CAT Tourniquets", "Pressure Dressings", "Bulky Dressings", "Over the Needle Catheters", "Vented Chest Seals", "Non-Vented Chest Seals", "Nasal Trumpet", "Oropharangeal-Airway", "Cric Kit", "Alcohol Swabs"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def quantity(self) -> int:
        """Gets the quantity of this Supplies.

        the number of these items available to the medic at the present time  # noqa: E501

        :return: The quantity of this Supplies.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this Supplies.

        the number of these items available to the medic at the present time  # noqa: E501

        :param quantity: The quantity of this Supplies.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
