

---

- name: Update and upgrade apt packages
  yum:
    update_cache: yes

# - name: copy service script
#   copy:
#     src: service/docker.service
#     dest: /etc/systemd/system/docker.service

# - name: change permission
#   shell: "chmod +x /etc/systemd/system/docker.service"

# - name: Reload Systemctl 
#   shell: "systemctl daemon-reload"

# - name: Add docker.service to autostart
#   shell: "systemctl enable docker.service"
- name: Ensure docker is installed and running
  yum:
    name: docker
    state: absent

- name: Ensure docker is installed and running
  yum:
    name: docker
    state: present

- name: Ensure docker group exists
  become: true
  group:
    name: docker
    state: present

- name: Ensure  user ec2-user is in docker group
  become: true
  user:
    name: "ec2-user"
    groups: docker
    append: true

- service:
    name: docker
    state: started
    enabled: yes
