

---

- name: Update and upgrade apt packages
  yum:
    # upgrade: yes
    update_cache: yes
    # cache_valid_time: 86400

- name: copy service script
  copy:
    src: service/docker.service
    dest: /etc/systemd/system/docker.service

- name: change permission
  shell: "chmod +x /etc/systemd/system/docker.service"

- name: Reload Systemctl 
  shell: "systemctl daemon-reload"

- name: Add docker.service to autostart
  shell: "systemctl enable docker.service"

- name: Ensure docker is installed and running
  yum:
    name: docker

- name: Ensure docker for user ec2-user
  become: true
  user:
    name: "ec2-user"
    groups: docker
    append: true

- service:
    name: docker
    state: started
    enabled: yes
