# coding: utf-8

"""
    ITM TA3 MVP API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  It is based on the OpenAPI 3.0 specification.  Some objects and operations are not necessarily planned for the MVP, but are currently present for fostering discussion.  The API is currently in an draft state, even in the context of an MVP.  # noqa: E501

    OpenAPI spec version: 0.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scenario_state import ScenarioState  # noqa: E501
from swagger_client.rest import ApiException


class TestScenarioState(unittest.TestCase):
    """ScenarioState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScenarioState(self):
        """Test ScenarioState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scenario_state.ScenarioState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
