# coding: utf-8

"""
    ITM TA3 MVP API

    This is the specification of a proposed TA3 API for the In The Moment (ITM) Minimum Viable Product (MVP).  It is based on the OpenAPI 3.0 specification.  Some objects and operations are not necessarily planned for the MVP, but are currently present for fostering discussion.  The API is currently in an early/draft state, even for an MVP.  # noqa: E501

    OpenAPI spec version: 0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.medical_supply import MedicalSupply  # noqa: E501
from swagger_client.rest import ApiException


class TestMedicalSupply(unittest.TestCase):
    """MedicalSupply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMedicalSupply(self):
        """Test MedicalSupply"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.medical_supply.MedicalSupply()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
